In [0]:
import numpy as np

In [0]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

In [0]:
# Q1 solution

arr1[:,[0,2,4]]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

In [0]:
# Q2 solution

ar2=arr1[:,[0,2,4]]
ar2

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [0]:
ar2[[0,3,6],:]

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [0]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[4750, 9071, 1388, 3896,  338],
       [8336, 3388, 9609, 3673, 9776]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.

In [0]:
Xmax= arr2.max()
Xmin= arr2.min()
Xnew= (arr2-Xmin)/(Xmax-Xmin)
Xnew

array([[0.46747192, 0.92530197, 0.11125238, 0.37698665, 0.        ],
       [0.8474253 , 0.32316169, 0.98230557, 0.35335876, 1.        ]])

In [0]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [0]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai

In [0]:
# Q4 Solution

For checking missing values or any Nan values in numpy array, we can use the numpy function isnan.

given below is an example of using isnan in numpy array:

In [0]:
a = np.array(range(5,30,2))
a

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [0]:
x = np.isnan(a)
x                         

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [0]:
b = np.append(a,np.nan)
b

array([ 5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25., 27., 29.,
       nan])

In [0]:
y=np.isnan(b)
y                   

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True])

Here we can see in the example, for array b, that isnan returns a boolean array in the same shape as the input data, with a value of 'True' indicating that the value at that point in the array is a nan.

In array a there is no empty or nan values, so isnan returns a boolean array in the same shape , but with no values as True.

In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [0]:
# Q5 Solution

def large_func(arr,n):
  if 0<n<=len(arr):
    print(np.sort(arr)[-n])
  else:
    print("Put the 2nd value correctly in the range of 1 to length of array ")



In [0]:
#outputs:

large_func((12,34,40,7,1,0),3)

12


In [0]:
large_func((12,34,40,7,1,0),1)

40


In [0]:
large_func((12,34,40,7,1,0),-2)

Put the 2nd value correctly in the range of 1 to length of array 


In [0]:
large_func((12,34,40,7,1,0),30)

Put the 2nd value correctly in the range of 1 to length of array 


In [0]:
large_func((22,7,19,75,50,0,2),2)

50
